### ISSUE TITLE
Text_displays.py errors with Pillow 10

### ISSUE THREAD

**Issue by guillermoaguilar** [computational-psychology/template_experiment#11]
Using pillow 9.5.0 it raises a deprecation warning:

/home/experimenter/template_experiment/5_asymmetric_matching/experiment/text_displays.py:50: DeprecationWarning: getsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use getbbox or getlength instead.

With Pillow 10 it raises an error.

**Comment by JorisVincent** [comment]
Closed by 3790cb6
